"""Repo-level paths and constants.

Audio and algorithm constants live in ``gmm/config.py``; this module re-exports
the ones used by repo-level scripts under the names they expect.
"""

from pathlib import Path
from gmm.config import (
    SAMPLE_RATE,
    N_FFT,
    LOG_OFFSET,
    HOP_LENGTH    as GMM_HOP_LENGTH,
    N_MELS        as GMM_N_MELS,
    CLIP_SECS     as MIMII_CLIP_SECS,
    SEED,
    N_TRAIN_CLIPS as TRAIN_CLIPS,
)

ROOT = Path(__file__).parent

# ── MIMII dataset roots (one per SNR level) ──────────────────────────────────
MIMII_NEG6DB_ROOT = ROOT / "data/mimii_neg6db"
MIMII_0DB_ROOT    = ROOT / "data/mimii_0db"
MIMII_6DB_ROOT    = ROOT / "data/mimii_6db"

# Split manifests generated by preprocessing/split_mimii.py.
MIMII_NEG6DB_SPLITS = ROOT / "preprocessing/outputs/mimii_splits/splits_neg6db.json"
MIMII_0DB_SPLITS    = ROOT / "preprocessing/outputs/mimii_splits/splits_0db.json"
MIMII_6DB_SPLITS    = ROOT / "preprocessing/outputs/mimii_splits/splits_6db.json"

# Default aliases used by gmm/evaluate.py when no root is passed explicitly.
MIMII_ROOT   = MIMII_NEG6DB_ROOT
MIMII_SPLITS = MIMII_NEG6DB_SPLITS

# ── Output directories ───────────────────────────────────────────────────────
GMM_NEG6DB_DIR = ROOT / "gmm/outputs/neg6db"
GMM_0DB_DIR    = ROOT / "gmm/outputs/0db"
GMM_6DB_DIR    = ROOT / "gmm/outputs/6db"
GMM_DIR        = GMM_NEG6DB_DIR

# ── MIMII machine config ─────────────────────────────────────────────────────
MACHINE_TYPES = ["fan", "pump", "slider", "valve"]
MACHINE_IDS   = ["id_00", "id_02", "id_04", "id_06"]

# ── Split sizing ─────────────────────────────────────────────────────────────
MONITOR_CLIPS = 30   # clips per monitoring window (5 min at 10 s/clip)
N_ROUNDS      = 3
